version: "2"
checks:
  method-complexity:
    config:
      threshold: 13
plugins:
  duplication:
    enabled: false
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
    config:
      threshold: "C"
