language: python
sudo: required
python:
  - "3.6"
services:
  - postgres
install:
  - pip install -U codeclimate-test-reporter pipenv
  - pipenv install --dev
  - pip install -I "coverage>4.0,<4.4"
script:
  - py.test
after_success:
  - CODECLIMATE_REPO_TOKEN=bd27affd4719a319a092fe65ad5ba8ba81f455d5f90821ccbcd30a9088e93577 codeclimate-test-reporter
